### ISSUE TITLE
Decun Upgrade

### ISSUE THREAD

**Issue by avalonche** [flashbots/builder#91]
# Task Tracking

Issue tracking for the Cancun Fork Upgrade for the builder.

* [ ] Rebase [deneb branch](https://github.com/flashbots/builder/tree/cancun-1.12.0) to [latest geth branch](https://github.com/MariusVanDerWijden/go-ethereum/tree/4844-devnet-6) for Deneb
* [ ] `flashbots_validateBuilderSubmissionV3` endpoint for block validation
* [ ] Verify blob length, blob validity (proof + commitments match with blob object), matching versioned blob hashes in txs with blob objects in the validation endpoint

## Dependencies

In PRs or not implemented yet.

### go-builder-client
- Fixing the ssz encoding for blob bundles https://github.com/attestantio/go-builder-client/pull/18
- `VersionedSubmitBlockRequest` types https://github.com/attestantio/go-builder-client/pull/15

### go-boost-utils
- Util functions to convert payload to payload headers https://github.com/flashbots/go-boost-utils/pull/87 
   - Will need to replace https://github.com/MariusVanDerWijden/go-ethereum/tree/4844-devnet-6 with latest geth release after the changes are merged

**Comment by bharath-123** [comment]
May I know what the status of this is? Which branch is the latest code for deneb in?

**Comment by bharath-123** [comment]
don't see the latest code in cancun-1.12.0

**Comment by avalonche** [comment]
https://github.com/flashbots/builder/tree/deneb
